name: "Configure aws CLI"
description: "Configure aws CLI"

inputs:
  aws_key_id:
    description: "Key id"
    required: true
  aws_secret_key_id:
    description: "Secret key id"
    required: true
  aws_default_region:
    description: "Default region"
    required: true
  aws_profile_name:
    description: "AWS CLI profile name"
    default: "amo"
    required: true

runs:
  using: composite
  steps:
    - name: Configuring aws CLI
      run: |
        aws configure --profile=${{ inputs.aws_profile_name }} set aws_access_key_id ${{ inputs.aws_key_id }}
        aws configure --profile=${{ inputs.aws_profile_name }} set aws_secret_access_key ${{ inputs.aws_secret_key_id }}
        aws configure --profile=${{ inputs.aws_profile_name }} set default.region ${{ inputs.aws_default_region }}
      shell: bash
