name: iac-ci

on:
  pull_request_review:
    types: [submitted]

env:
  TF_VERSION        : "1.2.7"
  TG_VERSION        : "v0.38.7"
  AWS_REGION        : "us-east-2"
  AWS_ROLE_TO_ASSUME: "arn:aws:iam::948691256895:role/gh-action"
  S3_BUCKET_NAME    : "rei-tf-state-s3"
  S3_BUCKET_KEY     : "pull-request"


jobs:
  get_changed_folder:
    runs-on: ubuntu-latest
    if: ${{ (github.event.review.state == 'approved') }}
    outputs:
      dir: ${{ steps.get_folder.outputs.dirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v25
        with:
          dir_names: "true"
          json: "true"

      - uses: actions/setup-python@v2
      - name: get_data_to_invoke_plan
        id: get_folder
        working-directory: ".github"
        run: |
          echo "::set-output name=dirs::$(python ./get_changed_folder.py --folders=${{ steps.changed-files-dir-names.outputs.modified_files }})"
  
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    continue-on-error: false
    needs: [get_changed_folder]
    strategy:
      max-parallel: 1
      matrix:
        dir: ${{fromJSON(needs.get_changed_folder.outputs.dir)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tf and tg
        uses: ./.github/actions/install-tf-tg
        with:
          tf_version: ${{ env.TF_VERSION }}
          tg_version: ${{ env.TG_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GithubActionsSession
      
      - name: Configure aws CLI profile
        uses: ./.github/actions/aws-configure
        with:
          aws_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key_id: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: ${{ env.AWS_DEFAULT_REGION }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}
          aws_profile_name: "amo"
      
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS_OF_GITHUB }}
      
      - name: Get plan
        working-directory: ${{ matrix.dir }}
        run: |
          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/${{ env.S3_BUCKET_KEY }}/${{ matrix.dir }}/${{ github.head_ref }}/data-with-plan.zip data-with-plan.zip --quiet
          unzip -q -u data-with-plan.zip
      
      - name: Apply infra
        working-directory: ${{ matrix.dir }}
        run: |
          echo "done"
        # echo "Y" | terragrunt run-all apply tfplan.file
