name: Tests

on:
  push:

jobs:
  get_changed_folder:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.get_folder.outputs.dirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v25
        with:
          dir_names: "true"
          json: "true"

      - uses: actions/setup-python@v2
      - name: get_data_to_invoke_plan
        id: get_folder
        working-directory: ".github"
        run: |
          echo "::set-output name=dirs::$(python ./get_changed_folder.py --folders=${{ steps.changed-files-dir-names.outputs.modified_files }})"

  make_plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    continue-on-error: false
    needs: [get_changed_folder]
    strategy:
      matrix:
        dir: ${{fromJSON(needs.get_changed_folder.outputs.dir)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing tfswitch
        run: |
          sudo apt install zip
          wget https://releases.hashicorp.com/terraform/1.2.7/terraform_1.2.7_linux_amd64.zip
          unzip terraform_1.2.7_linux_amd64.zip
          sudo mv terraform /usr/bin

      - name: Installing terragrunt
        run: |
          wget --quiet https://github.com/gruntwork-io/terragrunt/releases/download/v0.38.7/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: print version
        run: |
          terraform --version
          terragrunt --version

      - name: run plan
        working-directory: ${{ matrix.dir }}
        run: |
          ls -al

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::948691256895:role/gh-action
          role-session-name: GithubActionsSession

      - name: Copy index.html to s3
        run: |
          aws s3 ls
