name: Tests

on:
  push:

jobs:
  get_changed_folder:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.get_folder.outputs.dirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v25
        with:
          dir_names: "true"
          json: "true"

      - uses: actions/setup-python@v2
      - name: get_data_to_invoke_plan
        id: get_folder
        working-directory: ".github"
        run: |
          echo "::set-output name=dirs::$(python ./get_changed_folder.py --folders=${{ steps.changed-files-dir-names.outputs.modified_files }})"

  run_folder:
    runs-on: ubuntu-latest
    continue-on-error: false
    needs: [get_changed_folder]
    strategy:
      matrix:
        dir: ${{fromJSON(needs.get_changed_folder.outputs.dir)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing tfswitch
        run: |
          sudo apt install zip
          wget wget https://releases.hashicorp.com/terraform/1.2.7/terraform_1.2.7_linux_amd64.zip
          unzip terraform_1.2.7_linux_amd64.zip \
          sudo mv terraform /usr/bin \
#        run: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash

#      - name: Installing terragrunt
#        run: |
#          wget https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh
#          chmod 755 install.sh
#          ./install.sh -b $HOME/.bin
#          export PATH=$PATH:$HOME/.bin
#          tgswitch -b $HOME/.bin/terragrunt 0.38.0

      - name: Installing terragrunt
        run: |
          wget --quiet https://github.com/gruntwork-io/terragrunt/releases/download/v0.38.7/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

#      - name: install tf
#        run: |
#          tfswitch 1.2.6

#      - name: install tg
#        run: |
#          tgswitch 0.38.7

      - name: print version
        run: |
          terraform --version
          terragrunt --version

      - name: run plan
        working-directory: ${{ matrix.dir }}
        run: |
          ls -al
      
      
