name: Tests

on:
  push:

jobs:
  get_changed_folder:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.get_folder.outputs.dirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v25
        with:
          dir_names: "true"
          json: "true"

      - uses: actions/setup-python@v2
      - name: get_data_to_invoke_plan
        id: get_folder
        working-directory: ".github"
        run: |
          ls -al
          echo "::set-output name=dirs::$(python ./get_changed_folder.py --folders=${{ steps.changed-files-dir-names.outputs.modified_files }})"

  run_folder:
    runs-on: ubuntu-latest
    continue-on-error: false
    needs: [get_changed_folder]
    strategy:
      matrix:
        dir: ${{fromJSON(needs.get_changed_folder.outputs.dir)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Echo
        working-directory: ${{ matrix.dir }}
        run: |
          echo ${{needs.get_changed_folder.outputs.dir}}
          ls -al
      
      
