name: temp

on:
  workflow_dispatch:

jobs:
  get_reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            requests

      - name: get_data_to_invoke_plan
        id: get_reviewers
        working-directory: ".github"

        run: |
          python ./reviewers_manipulation.py --token ${{ secrets.GITHUB_TOKEN }}
  